spring.application.name=ClinicaOdont
server.error.include-message=always

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/clinica}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
